#ifndef BUFFERATTRIBUTES_H
#define BUFFERATTRIBUTES_H

enum BufferAttributes {
    VERTEX_BUFFER,
    COLOUR_BUFFER,
    NORMAL_BUFFER,
    INDEX_BUFFER,
    TEXTURE_BUFFER,
    BUFFER_COUNT
};

#endif // BUFFERATTRIBUTES_H
